# Generated by Django 4.2.23 on 2025-09-17 00:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Export",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
