# Generated by Django 4.2.23 on 2025-09-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_movie_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
